### ISSUE TITLE
Ethernet

### ISSUE THREAD

**Issue by DIMFLIX-OFFICIAL** [Zproger/bspwm-dotfiles#10]
В polybar не отображается иконка с ethernet, хотя он подключен. 
Порылся в конфигах полибара, а конкретнее в `config.ini`

там была строчка
`modules-right = battery xbacklight alsa xkeyboard round-left time round-right space wlan powermen`

Добавил в конец пункт ethernet
`modules-right = battery xbacklight alsa xkeyboard round-left time round-right space wlan ethernet powermen`

модуль отказывается работать и не появляется...
Есть какие-то решения этой проблемы?

**Comment by Zproger** [comment]
Ethernet еще не реализован в polybar, issue остается открытым до следующего обновления, если кто-то успеет реализовать быстрее, то закроем раньше. Добавил пункт в Projects.

**Comment by DIMFLIX-OFFICIAL** [comment]
Если кому-то срочно нужено управление подключениями ethernet, можете добавить мою версию скрипта:
https://github.com/DIMFLIX-OFFICIAL/rofi-sys-tools

В ридми есть примеры установки и внедрения в полибар.
