### ISSUE TITLE
Second language layout problem

### ISSUE THREAD

**Issue by kornevplus** [Zproger/bspwm-dotfiles#15]
## Суть проблемы

**Проблема:** На русской раскладке не работают стандартные хоткеи (Ctrl-C, Ctrl-V, Ctrl+W и тд.)

**Решение проблемы:** Измененние системы переключения раскладки с `setxkbmap` на `xkb-switch`

### 1. Установка пакета xkb-switch
Необходимо установить пакет **xkb-switch**. Лично я устанавливал с гитхаба путем компиляции, и у меня были проблемы с размещением библиотек, но решается это путем переноса библиотек libxkbswitch.so* из папки `/usr/local/lib/` в папку `/lib`

Возможно можно установить более простым способом.

### 2. Добавление раскладки x11
Далее для работы пакета xkb-switch нужно добавить раскладку командой `localectl --no-convert set-x11-keymap us,ru pc105`

Должен появиться файл `/etc/X11/xorg.conf.d/00-keyboard.conf` такого содержания: 
```bash
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "us,ru"
        Option "XkbModel" "pc105"
EndSection
```

После этого надо перезагрузить X сервер (перезайти в систему)

И проверить работает ли смена языка через команды `xkb-switch -s ru` и `xkb-switch -s us`
(Если в этот момент нажать Alt+Shift то конфиг собьется, и надо будет перезаходить)

### 3. Изменение скрипта по смене языка
Затем надо поменять скрипт который отвечает за смену раскладки хоткеями. Лично я сделал копию, чтобы иметь возможность в любой момент вернуться к предыдущего конфигу.

Создаем копию скрипта:
`cp ~/bin/change_language.sh ~/bin/change_language-xkb.sh`
Меняем новый скрипт:
`n ~/bin/change_language-xkb.sh`

Весь код меняем на это:

```bash
#! /bin/bash

CURRENT_LAYOUT=$(xkb-switch -p)

if [ "$CURRENT_LAYOUT" = "us" ]; then
    xkb-switch -s ru
	notify-send "Lang: RU" -t 700
else
    xkb-switch -s us
    notify-send "Lang: US" -t 700
fi
```

После этого надо внести изменения в файл с хоткеями: `n ~/.config/sxhkd/sxhkdrc`

В этом файле меняем путь до нашего нового скрипта вот в этом модуле:

```bash
# Change language
Alt_L + shift
 	sh $HOME/bin/change_language-xkb.sh

Shift_L + alt
 	sh $HOME/bin/change_language-xkb.sh
```
Полибар может сначала не отображать вторую раскладку, для этого надо его перезагрузить.

**Comment by Zproger** [comment]
Огромное спасибо за ваше решение. Также был ответ в Issue #5 через редактирование bash скрипта. Можно выбрать это решение, либо из issue #5 .
