### ISSUE TITLE
Make documentation in Russian

### ISSUE THREAD

**Issue by Krator3** [Zproger/bspwm-dotfiles#2]
Author, I am aware that you speak Russian. Then why don't you make a translation for the README file? That is, leave the original in English and at the very beginning give a link to the Russian version.

Автор, я знаю, что ты говоришь по-русски.  Тогда почему бы тебе не сделать перевод README файла?  То есть оставить оригинал на английском языке и в самом начале дать ссылку на русскую версию.

**Comment by Danrus1100** [comment]
Hi. first of all, this is not my project, but just a fork. and secondly, I
haven't managed to do anything yet because I didn't have my laptop with me.
if I customize the project for myself, I will definitely translate it

вс, 3 мар. 2024 г., 21:45 Maxim Ostapenko ***@***.***>:

**Comment by Zproger** [comment]
Hi, I'm trying to pretend I'm English.
And actually a translation into several languages is planned soon, please expect ;)))
I'm closing the question, as it's part of the roadmap (see Projects on the repository page).
