### ISSUE TITLE
как можно установить отдельно bin файлы

### ISSUE THREAD

**Issue by Miewkef** [Zproger/bspwm-dotfiles#32]
хотел бы установить только random_wallpapers но незнаю как

**Comment by DIMFLIX-OFFICIAL** [comment]
Просто копируешь из bin файлик random_wallpapers и ставишь к себе. 
Еще потребуется установить пакет `feh` чтобы всё работало

**Comment by Miewkef** [comment]
установил feh, скопировал в usr/bin, и изменил путь. А как сделать так чтобы оно через super+w работало :)

**Comment by Miewkef** [comment]
я из репы ничего не устанавливал

**Comment by DIMFLIX-OFFICIAL** [comment]
> установил feh, скопировал в usr/bin, и изменил путь. А как сделать так чтобы оно через super+w работало :)
> 

Вам нужно настроить ваш демон отслеживающий сочетания клавиш.
Если таковым является sxhkd, то на скриншоте вы можете увидеть конфигурацию.

![Screenshot_2024-06-09-11-08-00-86_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/Zproger/bspwm-dotfiles/assets/112165977/e11bd9fe-7635-4bf5-84e6-674d80a51e16)

**Comment by Miewkef** [comment]
как я понимаю у меня другой демон. или он в другом месте (os  fedora)
![Screenshot from 2024-06-09 13-18-15](https://github.com/Zproger/bspwm-dotfiles/assets/86587918/cc7c9fec-f615-4c06-8996-21ec7e69a7e9)

**Comment by DIMFLIX-OFFICIAL** [comment]
https://docs.fedoraproject.org/en-US/quick-docs/managing-keyboard-shortcuts-for-running-app-in-gnome/

**Comment by Miewkef** [comment]
я поставил как указано в гайде но не сработало. более того я попытался отдельно запустить бинарник и пропистаь в  терминал. ничего не меняет обои, но сама команда срабатывает

**Comment by Miewkef** [comment]
![Screenshot from 2024-06-09 13-40-52](https://github.com/Zproger/bspwm-dotfiles/assets/86587918/6d9c7bfc-d492-44ef-8505-6e6cc09ab325)

**Comment by DIMFLIX-OFFICIAL** [comment]
Возможно в федоре как-то иначе устанавливаются обои. 
Советую изучить информацию в интернете.
