### ISSUE TITLE
Проблема с emergency shell

### ISSUE THREAD

**Issue by kiritobtwq** [Zproger/bspwm-dotfiles#33]
Пробовал установить ваш арч, но похоже ошибся где-то. Поэтому попадаю в emergency shell.
Как зайти в Биос из emergency shell?
перед включением слишком быстро пропадает список с выбором, так ещё и монитор не успевает прогрузиться.
![IMG20240609162325.jpg](https://github.com/Zproger/bspwm-dotfiles/assets/72465942/8b8c4020-edf2-47fa-98c5-dc2f48330bee)

**Comment by DIMFLIX-OFFICIAL** [comment]
Не подскажите, - как решили проблему?
