### ISSUE TITLE
Черный екран арч линукс

### ISSUE THREAD

**Issue by Bublik-creator** [Zproger/bspwm-dotfiles#37]
Тупо черный екран даже курсора нету
![17215554059376744738122606731852](https://github.com/user-attachments/assets/68f35e48-df6e-4430-92c3-a1068e29eabe)

**Comment by Bublik-creator** [comment]
Даже нет курсора*

**Comment by Yuzmiev312** [comment]
Попробуй после того зашел под user написать sudo startx

**Comment by Bublik-creator** [comment]
А у меня вообще я включаю и просто черный екран

**Comment by Bublik-creator** [comment]
> Попробуй после того зашел под user написать sudo startx

У меня после етих задач
bootctl install --path=/boot
cd /boot/loader
micro loader.conf

# Вставляем в loader.conf следующий конфиг:
timeout 3
default arch

# Создаем конфигурацию для запуска
cd /boot/loader/entries
micro arch.conf

# Вставляем в arch.conf следующее:
# UUID можно узнать командой blkid
title Arch Linux by ZProger
linux /vmlinuz-linux
initrd /initramfs-linux.img
options rw cryptdevice=UUID=uuid_от_/dev/sda2:main root=/dev/mapper/main-root

# Выдаем права на sudo
sudo EDITOR=micro visudo
# После открытия раскомментируйте %wheel ALL=(ALL:ALL) ALL

# Выходим из системы и перезагружаемся
Ctrl+D
umount -R /mnt
reboot

Я перезагрузился и черный екран
