### ISSUE TITLE
Project mirror

### ISSUE THREAD

**Issue by Krator3** [Zproger/bspwm-dotfiles#4]
Hello! Have you thought about making a mirror for this project in Russian Git? They say that on March 20, Github may stop working in Russia. Maybe you should make a copy for example on GitFlic?

Здравствуйте!  Вы не думали сделать зеркало для этого проекта на русском Git?  Говорят, что 20 марта Github может перестать работать в России. Может стоит сделать копию например на GitFlic?

**Comment by Zproger** [comment]
At this stage, I am not prepared to support multiple repositories at once. To bypass the blocking you can use VPN, the project is in the public domain and does not require authorization.
