### ISSUE TITLE
четкость картинки в 1440p

### ISSUE THREAD

**Issue by lomik31** [Zproger/bspwm-dotfiles#42]
использовал kde большую часть времени и постоянно бесился с того что на этом же мониторе в macos шрифты красивые и гладкие, а у linux все время эти же шрифты либо зернистые либо расплывчатые. в общем, читать не очень приятно. на ютубе увидел очень приятные и нисколько не уступающие macos шрифты в этой сборке. однако, автор указывает, что сборка разработана под 1080p. хотел бы уточнить, есть ли пользователи мониторов 1440p 27 дюймов, как у вас с шрифтами обстоит вопрос? стоит ли пробовать ставить?

**Comment by goormany** [comment]
Проблема решена?
