### ISSUE TITLE
Нужна помочь

### ISSUE THREAD

**Issue by fLorzgg** [Zproger/bspwm-dotfiles#43]
Поставил эту оболочку на пк,но на polybar не отображаеться температура и нету дополнительных окон
![2024-09-02_17-24](https://github.com/user-attachments/assets/914e65a2-b2fc-4679-aacb-64b61292c9ff)

**Comment by DIMFLIX-OFFICIAL** [comment]
1. Какой процессор? Он может не передавать информацию о температуре.
2. Покажи конфиг ~/.config/bspwm/bspwmrc

**Comment by fLorzgg** [comment]
Процессор : Ryzen 5 3600
bspwmrc:

> #! /bin/sh
> 
> 
> pgrep -x sxhkd > /dev/null || sxhkd &
> 
> # fix some Java applications
> # wmname LG3D
> 
> # workspaces
> bspc monitor primary -d 1 2 3 4 5 6 7
> bspc monitor HDMI-0 -d 7  # TODO: multiple monitors
> 
> bspc config focus_follows_pointer true
> 
> # Window borders (Auto-Generate)
> bspc config focused_border_color "#7899FA"
> bspc config normal_border_color "#1f222b"
> bspc config border_width 5
> bspc config borderless_monocle true
> 
> bspc config active_border_color "#bd93f9"
> bspc config presel_feedback_color "#6272a4"
> 
> # fix pointer
> xsetroot -cursor_name left_ptr
> 
> # gaps
> bspc config gapless_monocle false
> bspc config window_gap 17
> 
> # moving floating windows and resize them with mouse, hold alt key
> bspc config pointer_modifier mod4
> bspc config pointer_action1 move
> bspc config pointer_action2 resize_side
> bspc config pointer_action3 resize_corner
> 
> # rules
> bspc rule -a feh state=floating
> # bspc rule -a firefox state=floating
> # bspc rule -a firefox desktop='^2' follow=on
> 
> # start resources
> xrdb merge ~/.Xresources
> 
> # python script to always initialize with a different wallpaper:
> # TODO: Add loading of basic scripts
> ~/.config/bspwm/scripts/launch.sh &
> ~/.config/polybar/launch.sh
> 
> # launch notification daemon
> dunst -config $HOME/.config/bspwm/dunstrc &
> 
> # launch battery tracker and redshift
> pkill battery-alert; ~/bin/battery-alert &
> pgrep -x redshift > /dev/null || redshift &
> 
> # start compositor
> picom --config $HOME/.config/bspwm/picom_configurations/1.conf &
> 
> # autostart
> flameshot &

**Comment by fLorzgg** [comment]
И кстати у меня еще проблемы с настройками монитора,когда меняю герцовку то ничего не изменяеться,даже экран не тухнет

**Comment by DIMFLIX-OFFICIAL** [comment]
> И кстати у меня еще проблемы с настройками монитора,когда меняю герцовку то ничего не изменяеться,даже экран не тухнет

С помощью чего меняешь параметры? xrandr?

**Comment by fLorzgg** [comment]
вроде как,чисто в rofi выбираю дисплей и там меняю

**Comment by fLorzgg** [comment]
bspwmrc : 
```
#! /bin/sh


pgrep -x sxhkd > /dev/null || sxhkd &

# fix some Java applications
# wmname LG3D

# workspaces
bspc monitor primary -d 1 2 3 4 5 6 7
bspc monitor HDMI-0 -d 7  # TODO: multiple monitors

bspc config focus_follows_pointer true

# Window borders (Auto-Generate)
bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"
bspc config border_width 5
bspc config borderless_monocle true

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

# fix pointer
xsetroot -cursor_name left_ptr

# gaps
bspc config gapless_monocle false
bspc config window_gap 17

# moving floating windows and resize them with mouse, hold alt key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# rules
bspc rule -a feh state=floating
# bspc rule -a firefox state=floating
# bspc rule -a firefox desktop='^2' follow=on

# start resources
xrdb merge ~/.Xresources

# python script to always initialize with a different wallpaper:
# TODO: Add loading of basic scripts
~/.config/bspwm/scripts/launch.sh &
~/.config/polybar/launch.sh

# launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# launch battery tracker and redshift
pkill battery-alert; ~/bin/battery-alert &
pgrep -x redshift > /dev/null || redshift &

# start compositor
picom --config $HOME/.config/bspwm/picom_configurations/1.conf &

# autostart
flameshot &
```

**Comment by DIMFLIX-OFFICIAL** [comment]
> bspwmrc :
> 
> ```
> #! /bin/sh
> 
> 
> pgrep -x sxhkd > /dev/null || sxhkd &
> 
> # fix some Java applications
> # wmname LG3D
> 
> # workspaces
> bspc monitor primary -d 1 2 3 4 5 6 7
> bspc monitor HDMI-0 -d 7  # TODO: multiple monitors
> 
> bspc config focus_follows_pointer true
> 
> # Window borders (Auto-Generate)
> bspc config focused_border_color "#7899FA"
> bspc config normal_border_color "#1f222b"
> bspc config border_width 5
> bspc config borderless_monocle true
> 
> bspc config active_border_color "#bd93f9"
> bspc config presel_feedback_color "#6272a4"
> 
> # fix pointer
> xsetroot -cursor_name left_ptr
> 
> # gaps
> bspc config gapless_monocle false
> bspc config window_gap 17
> 
> # moving floating windows and resize them with mouse, hold alt key
> bspc config pointer_modifier mod4
> bspc config pointer_action1 move
> bspc config pointer_action2 resize_side
> bspc config pointer_action3 resize_corner
> 
> # rules
> bspc rule -a feh state=floating
> # bspc rule -a firefox state=floating
> # bspc rule -a firefox desktop='^2' follow=on
> 
> # start resources
> xrdb merge ~/.Xresources
> 
> # python script to always initialize with a different wallpaper:
> # TODO: Add loading of basic scripts
> ~/.config/bspwm/scripts/launch.sh &
> ~/.config/polybar/launch.sh
> 
> # launch notification daemon
> dunst -config $HOME/.config/bspwm/dunstrc &
> 
> # launch battery tracker and redshift
> pkill battery-alert; ~/bin/battery-alert &
> pgrep -x redshift > /dev/null || redshift &
> 
> # start compositor
> picom --config $HOME/.config/bspwm/picom_configurations/1.conf &
> 
> # autostart
> flameshot &
> ```

На 10 строчке убери primary и перезапусти bspwm (ctrl+shift+r)

**Comment by DIMFLIX-OFFICIAL** [comment]
> вроде как,чисто в rofi выбираю дисплей и там меняю

На счёт rofi не знаю что ты юзаешь. Попробуй xrandr.
Вот доки https://wiki.archlinux.org/title/Xrandr

**Comment by fLorzgg** [comment]
в bspwmrc удалил 10 строчку,но ничего не поменялось
![2024-09-02_22-12](https://github.com/user-attachments/assets/461fe1d4-e0e4-4727-af35-165fab8765ad)

**Comment by DIMFLIX-OFFICIAL** [comment]
Добавь изменение параметров экрана в bspwmrc.
А по поводу рабочих пространств вон у тебя цифра 7 появилась. Мне кажется тебе еще полибар нужно перезапустить.

**Comment by fLorzgg** [comment]
1.Как бы правильно закинуть этот скрипт в bspwmrc
2.Цифра 7 еще появилась тогда когда я в bspwmrc поменял `bspc monitor LVDS-1 -d 7` на `bspc monitor HDMI-0 -d 7`

**Comment by DIMFLIX-OFFICIAL** [comment]
1. просто пропиши команду изменения монитора с помощью xrandr в bspwmrc например в самый конец файла и всё
2. Поменяй на `bspc monitor HDMI-0 -d 1 2 3 4 5 6 7` и будут все рабочие столы.

**Comment by fLorzgg** [comment]
Окей,ща комп рестартну и гляну

**Comment by fLorzgg** [comment]
```
[module/cpu]
type = custom/script
exec = "python PATH_TO_SCRIPT --cpu --normal-color "#f5c2e7" --critical-color "#f38ba8""
click-left = "python PATH_TO_SCRIPT --cpu --click"
format = "<label>  "
interval = 2
format-background = ${colors.sbg}
```
Что вставить на место `python PATH_TO_SCRIPT`?

**Comment by DIMFLIX-OFFICIAL** [comment]
Путь до питон скрипта. 
Я тебе скинул код. Создай какой-нибудь файлик и вставь туда этот код. 
Здесь укажи путь к файлу.

Прошлый cpu можешь убрать.
Но скорее всего у тебя не отображается температура из-за того что сам процессор не передает инфы по ней. 
У меня такая-же тема с ryzen5500u

**Comment by fLorzgg** [comment]
Окей,тогда ничего менять не буду.Слушай,не можно твоего дискорда?А то я новичек в линуксе,не оч разбираюсь с конфигами

**Comment by DIMFLIX-OFFICIAL** [comment]
Дискордом не особо часто пользуюсь. Лучше телега. 
Ссылка в профиле у меня.

**Comment by fLorzgg** [comment]
Тогда я закрываю этот тикет,напишу когда надо будет,удачи!Большое спасибо за помощь
