### ISSUE TITLE
Комбинации клавиш работают только на одной раскладке

### ISSUE THREAD

**Issue by timur438** [Zproger/bspwm-dotfiles#5]
Комбинации для выделения, копирования, вставки и может другие, не проверял, работают только на английской раскладке. Проблему решил но может быть кому-то поможет.

## Решение:
Помогло убрать кавычки из команды setxkbmap в скрипте $HOME/bin/change_language.sh
### Было:
```
#! /bin/bash

CURRENT_LAYOUT=$(setxkbmap -query | awk -F : 'NR==3{print $2}' | sed 's/ //g')

if [ "$CURRENT_LAYOUT" = "us" ]; then
    setxkbmap "ru"
	notify-send "Lang: RU" -t 700
else
    setxkbmap "us"
    notify-send "Lang: US" -t 700
fi
```
### Стало:
```
#! /bin/bash

CURRENT_LAYOUT=$(setxkbmap -query | awk -F : 'NR==3{print $2}' | sed 's/ //g')

if [ "$CURRENT_LAYOUT" = "us" ]; then
    setxkbmap ru
	notify-send "Lang: RU" -t 700
else
    setxkbmap us
    notify-send "Lang: US" -t 700
fi
```

**Comment by Zproger** [comment]
Спасибо за решение. Сегодня пытался исправить эту ошибку, не нашел готовых решений. Пытался делать middle layer, но оно отказывается работать. Насколько я знаю, эта проблема связана именно с некоторыми GTK / QT софтами, которые не принимают русские комбинации клавиш.

Я пытался проверить работоспособность вашего решения, у меня все равно это не работает. Проверьте пожалуйста как работает ctrl+c / ctrl+v к примеру в том же firefox или telegram используя русскую раскладку.

**Comment by timur438** [comment]
> Я пытался проверить работоспособность вашего решения, у меня все равно это не работает. Проверьте пожалуйста как работает ctrl+c / ctrl+v к примеру в том же firefox или telegram используя русскую раскладку.

Только что обновил через pacman, перезагрузил и перестало работать, видимо на работу повлияло не мое решение выше, а что-то еще, пока не могу понять что

**Comment by nevgleb** [comment]
Решение, которое помогло мне, и возможно поможет кому-то еще, файл  $HOME/bin/change_language.sh
### Решение
`#!/bin/bash

CURRENT_LAYOUT=$(xset -q|grep LED| awk '{ print $10 }')

setxkbmap -layout us,ru -option "grp:alt_shift_toggle"
if [ "$CURRENT_LAYOUT" = "00000000" ]; then
	notify-send "Lang: US" -t 700
fi

if [ "$CURRENT_LAYOUT" = "00001000" ]; then
    notify-send "Lang: RU" -t 700
fi`

**Comment by Zproger** [comment]
> Решение, которое помогло мне

Огромная благодарность за ваш вклад. Это помогло решить проблему.
