### ISSUE TITLE
Не работает переключение между рабочими столами

### ISSUE THREAD

**Issue by DIMFLIX-OFFICIAL** [Zproger/bspwm-dotfiles#7]
Поставил сборку. Вроде со всеми проблемами разобрался, но осталась главная.. У меня вообще не работает переключение между рабочими столами. Да их даже просто нет... Что делать?
![2024-04-20_18-02](https://github.com/Zproger/bspwm-dotfiles/assets/112165977/e311a07e-bc10-4c23-a417-6c497d715f16)

**Comment by EthanPlayerOne** [comment]
Точно такая же ошибка после свежей установки. Если будут какие-то идеи, дайте знать плиз

**Comment by EthanPlayerOne** [comment]
Я перезапустил Polybar, никаких критичных ошибок я не заметил, но рабочих столов все еще нет. Ошибка 100% в настройках внешки самого полибара.

**Comment by Savelysp** [comment]
у меня была такая ошибка, я вроде поиграл в конфиге bspwm и polybar и оно пропало, но из-за какого конкретно действия, я не понял

**Comment by EthanPlayerOne** [comment]
> у меня была такая ошибка, я вроде поиграл в конфиге bspwm и polybar и оно пропало, но из-за какого конкретно действия, я не понял
 
@Savelysp, есть возможность сравнить файлы из репозитория, с теми, что были изменены? Или целиком файлы кинуть? 
Я тоже игрался и с полибаром и с bspwm но резульата не получил :(

**Comment by Savelysp** [comment]
> > у меня была такая ошибка, я вроде поиграл в конфиге bspwm и polybar и оно пропало, но из-за какого конкретно действия, я не понял
> 
> @Savelysp, есть возможность сравнить файлы из репозитория, с теми, что были изменены? Или целиком файлы кинуть? Я тоже игрался и с полибаром и с bspwm но резульата не получил :(

попробуй в ~/.config/bspwm/bspwmrc заменить
```
# workspaces
bspc monitor primary -d 1 2 3 4 5 6 7
bspc monitor LVDS-1 -d 7  # TODO: multiple monitors
``` 
на
```
# workspaces
bspc monitor -d 1 2 3 4 5 6 7
```

**Comment by Zproger** [comment]
Как отмечалось выше, проблема решается путем удаления флага `primary` в `~/.config/bspwm/bspwmrc`, попробуйте поэкспериментировать с этим. Также не забывайте перезапускать BPSWM после внесения изменений. Если проблема решена, дайте знать в комментариях.

**Comment by EthanPlayerOne** [comment]
Да, все работает. Спасибо! ❤️
