### ISSUE TITLE
Недочет в Rofi меню

### ISSUE THREAD

**Issue by DIMFLIX-OFFICIAL** [Zproger/bspwm-dotfiles#8]
При нажати super + d открывается Rofi меню. 
Недочет заключается в том, что именно при фокусе на этом окне невозможно поменять раскладку клавиатуры.

**Comment by Zproger** [comment]
В обновлении 1.1 ошибка исправлена. В Rofi не используется русская раскладка, поэтому решение состоит в редактировании `~/.config/sxhkd/sxhkdrc`, сделайте замену этой строки:

# Launch Rofi Menu
```
super + {d,x}
    {setxkbmap -layout us; rofi -show drun,sh $HOME/bin/powermenu}
```
    
Обновление 1.1 недоступно на момент открытия Issue, поэтому прикрепляю решение. В дальнейшем прошу проверять "Projects", чтобы посмотреть уже решенные проблемы.

**Comment by DIMFLIX-OFFICIAL** [comment]
Не работает. Просто утсанавливается автоматически на английскую и все. Менять с помощью горячих клавиш Shift + Alt невозможно. 
И кстати, если поставить вместо us - ru, то автоматически язык будет русский, но это не отображается на полибаре сверху и так-же невозможно менять при помощи shift + alt

**Comment by Zproger** [comment]
Здесь решение заключается в том, чтобы не приходилось переключать раскладку при запуске rofi-menu, все приложения на английском языке, я не припомню, чтобы хоть 1 приложение называлось на русском, поэтому установка английской раскладки решает проблему. Если смотреть в сторону того, чтобы можно было вызывать комбинации клавиш при запуске рофи, то думаю стоит открыть issue уже в проекте rofi-menu, так как я не нашел решение этой проблемы.
